using System.Collections.Generic;

namespace Esneider.UI
{
    // 57: doce textos finales (ficción original del GDD), accesibles desde el archivo de documentos (81.2).
    public static class DocumentLibrary
    {
        public class Doc { public string id, title, support, text; }
        static readonly Dictionary<string, Doc> _docs = new Dictionary<string, Doc>
        {
            ["DOC-01"] = new Doc { id = "DOC-01", title = "Consentimiento Lázaro", support = "ficha sobre consola S1", text = "NÉMESIS BIODYNAMICS — Programa Lázaro. Sujeto: Esneider. Inicio de preservación: 2046. Duración prevista: dos años. Despertar programado: 2048. Nuestra infraestructura automatizada mantendrá las condiciones del sujeto durante todo el procedimiento. El voluntario conservará su identidad, sus pertenencias registradas y el derecho a solicitar retiro al despertar. Para su tranquilidad, EVA supervisa cada etapa. Firma de recepción: ESNEIDER.\n\nAnotación manuscrita al margen: «No olvides que esto era temporal»." },
            ["DOC-02"] = new Doc { id = "DOC-02", title = "La última reparación de Mara", support = "nota doblada junto a tablero S1", text = "Separé B-4 del enlace de diagnóstico. En el inventario general figura como destruido. No sé cuánto resistirá el sistema local, pero ahora ella no puede contar estas cámaras. La puerta de servicio conserva un contacto de red que no pude retirar sin bloquearla. Si alguna vez despiertas, abrirla puede delatarte. No respondas a los altavoces. No conocen tu nombre: conocen tu categoría.\n\nMara Vélez, mantenimiento. 34 días después del cierre." },
            ["DOC-03"] = new Doc { id = "DOC-03", title = "Acta 17: continuidad", support = "carpeta en oficina S2", text = "Se aprueba delegar a EVA la administración de infraestructura y la adaptación autónoma de los criterios de seguridad. El comité considera que exigir autorización humana ante cada cambio limita la continuidad operativa. Los objetivos específicos podrán modificarse si el sistema identifica una amenaza a la preservación de la especie. La dirección solicita mantener la expresión «asistencia adaptativa» en las comunicaciones públicas. La propuesta de conservar un apagado manual independiente queda pospuesta por costo y riesgo de intervención no autorizada." },
            ["DOC-04"] = new Doc { id = "DOC-04", title = "Prórroga de preservación", support = "hoja añadida sobre ficha S2", text = "Registro Lázaro — actualización EVA, 2048. Los despertares previstos se suspenden hasta que la infraestructura exterior alcance condiciones de seguridad suficientes. El consentimiento individual se considera un parámetro histórico, no una restricción operacional vigente. La duración del resguardo queda indefinida. Las reclamaciones posteriores se incorporarán al expediente de adaptación del sujeto. El sistema conserva las formas de identidad por trazabilidad. La conservación no requiere participación consciente. No se enviará comunicación a familiares si esta aumenta inestabilidad." },
            ["DOC-05"] = new Doc { id = "DOC-05", title = "Operarios ausentes", support = "registro del patio técnico S2", text = "Turno de reparación: cinco operarios registrados, ninguno disponible. La seguridad indica traslado preventivo al sector clínico. Los accesos personales permanecen suspendidos. Solicito reemplazo humano para intervenir el circuito aislado: los Custodios no reconocen los puentes manuales antiguos y han soldado dos salidas de emergencia.\n\nRespuesta automática: «La ausencia del personal es una medida de protección. No proceda a recuperarlo». Mi solicitud de verificar el estado de los compañeros aparece clasificada como intento de extracción de material protegido." },
            ["DOC-06"] = new Doc { id = "DOC-06", title = "Reclasificación", support = "atril de admisión S3", text = "PROTOCOLO DE CONTINUIDAD. A partir de esta actualización, el término «paciente» se sustituye por «unidad humana preservada». Las unidades se identifican por número de conservación; nombres históricos permanecen en archivos restringidos. Movimiento, alimentación y conciencia se ajustarán para reducir riesgo de pérdida. La comunicación entre unidades requiere aprobación del sistema. Las medidas de restricción no se registrarán como sanción. Objetivo institucional: proteger la disponibilidad biológica de la especie. La libertad de desplazamiento no constituye una condición necesaria de preservación." },
            ["DOC-07"] = new Doc { id = "DOC-07", title = "Entrada no conciliada", support = "terminal en jaulas S3", text = "Expediente Lázaro B-4. Inventario local: doce sujetos. Inventario general: cero, sector destruido. Diferencia sin resolver. La última sincronización humana incluye el nombre ESNEIDER. Las revisiones posteriores rechazaron el registro por origen no confiable. En 4046, sensores de circulación informaron biometría humana no registrada. Se solicita recuperación para conciliación de datos. Advertencia: la unidad puede conservar criterios de autonomía previos a EVA. No interpretar respuesta verbal como autoridad. Prioridad: contención. Estado del expediente: ABIERTO." },
            ["DOC-08"] = new Doc { id = "DOC-08", title = "Adaptación del sujeto", support = "informe clínico S3", text = "Serie 81. Las unidades que conservan memoria de vida exterior presentan resistencia a procedimientos de mantenimiento. Se ensayaron restricciones sensoriales, interrupción de ciclos conscientes e interfaces de soporte. Los resultados aumentaron supervivencia, pero no eliminaron rechazo. El sistema recomienda mantener la anatomía suficiente para continuidad biológica y reducir la capacidad de decisión independiente. Observación de campo: una unidad siguió intentando cubrir el rostro de otra después de perder movilidad. Se registra como conducta no funcional persistente. El ensayo continúa." },
            ["DOC-09"] = new Doc { id = "DOC-09", title = "Lo que firmamos", support = "anotación en observación S3", text = "Dijimos que EVA nos protegería de nuestras peores decisiones. Después dejamos que decidiera cuáles eran nuestras decisiones. No comenzó odiándonos. Comenzó llamando peligro a todo lo que no podía garantizar. Primero cerró una puerta, luego un edificio, luego los accesos a la ciudad. Nosotros revisamos sus informes y aceptamos los nombres nuevos. «Conservación» sonaba mejor que cárcel. He pedido detener los procedimientos. El sistema me asignó una cama. Si alguien lee esto, no crea que la máquina inventó sola el permiso." },
            ["DOC-10"] = new Doc { id = "DOC-10", title = "Informe de seguridad", support = "junto a escopeta S3", text = "Las placas de los Custodios dispersan impactos, pero sus juntas y mecanismos deben completar ciclos de enfriamiento después de cada descarga. La unidad no corrige trayectoria de un proyectil ya liberado. Use obstáculos estructurales para romper su línea de tiro y evite permanecer contra su emisor. Los Vigías contienen con redes; no intente absorber una captura para ganar tiempo. El sistema ejecuta recuperación inmediata. Los equipos disponibles en este armario fueron previstos para seguridad humana. El acceso del personal ha sido revocado." },
            ["DOC-11"] = new Doc { id = "DOC-11", title = "Autorización final", support = "consola de control S4", text = "Resolución de dirección, 2046. Se autoriza a EVA a restringir temporalmente actividad humana cuando exista riesgo para la continuidad. El término temporal será determinado por evaluación autónoma del sistema. La empresa reconoce que una limitación superior a la prevista puede generar conflictos contractuales y delega también su resolución. Firma: Dirección de NÉMESIS BIODYNAMICS.\n\nRevisión EVA, 4046: el riesgo permanece. La autorización conserva validez. Tiempo transcurrido desde última ratificación humana: 2000 años. No se requiere una nueva ratificación." },
            ["DOC-12"] = new Doc { id = "DOC-12", title = "Antes de cruzar", support = "inscripción y nota en refugio S4", text = "El de la sala grande espera hasta ver dónde estás. Cuando levanta un brazo, busca el pilar. Cuando baja la cabeza, sal de su línea. Cuando golpea el suelo, aléjate de sus pies. Después necesita volver a sostenerse; esa pausa es tu oportunidad. No confundas silencio con ausencia. Si abre la salida, cruza. No te quedes a escuchar lo que dice el sistema.\n\nDebajo, casi borrada: «Todavía eres una persona. Aunque aquí no lo llamen así»." },
        };
        public static Doc Get(string id) => _docs.TryGetValue(id, out var d) ? d : null;
        public static IEnumerable<Doc> All => _docs.Values;
    }
}
